name: Bump version, build and release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    runs-on: ubuntu-latest
    name: 'Bump version and create changelog with commitizen'
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: '${{ secrets.PAT }}'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PAT }}
          changelog_increment_filename: body.md
          push: false
      - name: Build
        run: |
          git config --global user.name 'Rui Araújo'
          git config --global user.email 'ruiaraujo012@users.noreply.github.com'
          pnpm run build
          git add .
          git commit -m "bump: bump and build ${{ env.REVISION }}"
          git push
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: 'body.md'
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
