name: Bump version, build and release

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PAT }}"
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Get next version
        run: pnpm semantic-release --no-ci --dy-run
        env:
          GH_TOKEN: ${{ secrets.PAT}}
      - name: Build
        env:
          APP_VERSION: ${{ env.NEXT_RELEASE_VERSION }}
        run: pnpm build
      - name: Zip dist folder
        run: zip -r dist.zip dist
      - name: Release
        run: pnpm semantic-release
        env:
          GH_TOKEN: ${{ secrets.PAT}}
